name: 'Run all tests'
'on':
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  test:
    name: 'Run tests'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3.5.3'
      - name: 'Setup Pnpm'
        uses: 'pnpm/action-setup@v2'
      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v3'
        with:
          node-version: '20'
      - name: 'Install Dependencies'
        run: 'pnpm install'
      - name: 'Run tests'
        run: 'npm run test'
